typedef enum {
    PokeBall, GreatBall, Ultraball
} Ball;

int ball_modifier[] = {12, 8, 12};

typedef enum {
    Bulbasaur, Ivysaur, Venusaur, Charmander, Charmeleon, Charizard, Squirtle, Wartortle, Blastoise,
    Caterpie, Metapod, Butterfree, Weedle, Kakuna, Beedrill, Pidgey, Pidgeotto, Pidgeot,
    Rattata, Raticate, Spearow, Fearow, Ekans, Arbok, Pikachu, Raichu, Sandshrew, 
    Sandslash, NidoranF, Nidorina, Nidoqueen, NidoranM, Nidorino, Nidoking, Clefairy, Clefable, 
    Vulpix, Ninetales, Jigglypuff, Wigglytuff, Zubat, Golbat, Oddish, Gloom, Vileplume, 
    Paras, Parasect, Venonat, Venomoth, Diglett, Dugtrio, Meowth, Persian, Psyduck, 
    Golduck, Mankey, Primeape, Growlithe, Arcanine, Poliwag, Poliwhirl, Poliwrath, Abra, 
    Kadabra, Alakazam, Machop, Machoke, Machamp, Bellsprout, Weepinbell, Victreebel, Tentacool, 
    Tentacruel, Geodude, Graveler, Golem, Ponyta, Rapidash, Slowpoke, Slowbro, Magnemite,
    Magneton, Farfetchd, Doduo, Dodrio, Seel, Dewgong, Grimer, Muk, Shellder,
    Cloyster, Gastly, Haunter, Gengar, Onix, Drowzee, Hypno, Krabby, Kingler,
    Voltorb, Electrode, Exeggcute, Exeggutor, Cubone, Marowak, Hitmonlee, Hitmonchan, Lickitung, 
    Koffing, Weezing, Rhyhorn, Rhydon, Chansey, Tangela, Kangaskhan, Horsea, Seadra,
    Goldeen, Seaking, Staryu, Starmie, MrMime, Scyther, Jynx, Electabuzz, Magmar,
    Pinsir, Tauros, Magikarp, Gyarados, Lapras, Ditto, Eevee, Vaporeon, Jolteon,
    Flareon, Porygon, Omanyte, Omastar, Kabuto, Kabutops, Aerodactyl, Snorlax, Articuno,
    Zapdos, Moltres, Dratini, Dragonair, Dragonite, Mewtwo, Mew
} PokemonName;

typedef struct {
    const char *name;
    int max_health;
    int catch_rate;
} Pokemon;

Pokemon pokemon_data[] = {
    {.name = "Bulbasaur", .max_health = 45, .catch_rate = 45},
    {.name = "Ivysaur", .max_health = 60, .catch_rate = 45},
    {.name = "Venusaur", .max_health = 80, .catch_rate = 45},
    {.name = "Charmander", .max_health = 39, .catch_rate = 45},
    {.name = "Charmeleon", .max_health = 58, .catch_rate = 45},
    {.name = "Charizard", .max_health = 78, .catch_rate = 45},
    {.name = "Squirtle", .max_health = 44, .catch_rate = 45},
    {.name = "Wartortle", .max_health = 59, .catch_rate = 45},
    {.name = "Blastoise", .max_health = 79, .catch_rate = 45},
    {.name = "Caterpie", .max_health = 45, .catch_rate = 255},
    {.name = "Metapod", .max_health = 50, .catch_rate = 120},
    {.name = "Butterfree", .max_health = 60, .catch_rate = 45},
    {.name = "Weedle", .max_health = 40, .catch_rate = 255},
    {.name = "Kakuna", .max_health = 45, .catch_rate = 120},
    {.name = "Beedrill", .max_health = 65, .catch_rate = 45},
    {.name = "Pidgey", .max_health = 40, .catch_rate = 255},
    {.name = "Pidgeotto", .max_health = 63, .catch_rate = 120},
    {.name = "Pidgeot", .max_health = 83, .catch_rate = 45},
    {.name = "Rattata", .max_health = 30, .catch_rate = 255},
    {.name = "Raticate", .max_health = 55, .catch_rate = 127},
    {.name = "Spearow", .max_health = 40, .catch_rate = 255},
    {.name = "Fearow", .max_health = 65, .catch_rate = 90},
    {.name = "Ekans", .max_health = 35, .catch_rate = 255},
    {.name = "Arbok", .max_health = 60, .catch_rate = 90},
    {.name = "Pikachu", .max_health = 35, .catch_rate = 190},
    {.name = "Raichu", .max_health = 60, .catch_rate = 75},
    {.name = "Sandshrew", .max_health = 50, .catch_rate = 255},
    {.name = "Sandslash", .max_health = 75, .catch_rate = 90},
    {.name = "NidoranF", .max_health = 55, .catch_rate = 235},
    {.name = "Nidorina", .max_health = 70, .catch_rate = 120},
    {.name = "Nidoqueen", .max_health = 90, .catch_rate = 45},
    {.name = "NidoranM", .max_health = 46, .catch_rate = 235},
    {.name = "Nidorino", .max_health = 61, .catch_rate = 120},
    {.name = "Nidoking", .max_health = 81, .catch_rate = 45},
    {.name = "Clefairy", .max_health = 70, .catch_rate = 150},
    {.name = "Clefable", .max_health = 95, .catch_rate = 25},
    {.name = "Vulpix", .max_health = 38, .catch_rate = 190},
    {.name = "Ninetales", .max_health = 73, .catch_rate = 75},
    {.name = "Jigglypuff", .max_health = 115, .catch_rate = 170},
    {.name = "Wigglytuff", .max_health = 140, .catch_rate = 50},
    {.name = "Zubat", .max_health = 40, .catch_rate = 255},
    {.name = "Golbat", .max_health = 75, .catch_rate = 90},
    {.name = "Oddish", .max_health = 45, .catch_rate = 255},
    {.name = "Gloom", .max_health = 60, .catch_rate = 90},
    {.name = "Vileplume", .max_health = 75, .catch_rate = 255},
    {.name = "Paras", .max_health = 35, .catch_rate = 190},
    {.name = "Parasect", .max_health = 60, .catch_rate = 75},
    {.name = "Venonat", .max_health = 60, .catch_rate = 190},
    {.name = "Venomoth", .max_health = 70, .catch_rate = 75},
    {.name = "Diglett", .max_health = 10, .catch_rate = 255},
    {.name = "Dugtrio", .max_health = 35, .catch_rate = 50},
    {.name = "Meowth", .max_health = 40, .catch_rate = 255},
    {.name = "Persian", .max_health = 65, .catch_rate = 90},
    {.name = "Psyduck", .max_health = 50, .catch_rate = 190},
    {.name = "Golduck", .max_health = 80, .catch_rate = 75},
    {.name = "Mankey", .max_health = 40, .catch_rate = 190},
    {.name = "Primeape", .max_health = 65, .catch_rate = 75},
    {.name = "Growlithe", .max_health = 55, .catch_rate = 190},
    {.name = "Arcanine", .max_health = 90, .catch_rate = 75},
    {.name = "Poliwag", .max_health = 40, .catch_rate = 255},
    {.name = "Poliwhirl", .max_health = 65, .catch_rate = 120},
    {.name = "Poliwrath", .max_health = 90, .catch_rate = 45},
    {.name = "Abra", .max_health = 25, .catch_rate = 200},
    {.name = "Kadabra", .max_health = 40, .catch_rate = 100},
    {.name = "Alakazam", .max_health = 55, .catch_rate = 50},
    {.name = "Machop", .max_health = 70, .catch_rate = 180},
    {.name = "Machoke", .max_health = 80, .catch_rate = 90},
    {.name = "Machamp", .max_health = 90, .catch_rate = 45},
    {.name = "Bellsprout", .max_health = 50, .catch_rate = 255},
    {.name = "Weepinbell", .max_health = 65, .catch_rate = 120},
    {.name = "Victreebel", .max_health = 80, .catch_rate = 45},
    {.name = "Tentacool", .max_health = 40, .catch_rate = 190},
    {.name = "Tentacruel", .max_health = 80, .catch_rate = 60},
    {.name = "Geodude", .max_health = 40, .catch_rate = 255},
    {.name = "Graveler", .max_health = 55, .catch_rate = 120},
    {.name = "Golem", .max_health = 80, .catch_rate = 45},
    {.name = "Ponyta", .max_health = 50, .catch_rate = 190},
    {.name = "Rapidash", .max_health = 65, .catch_rate = 60},
    {.name = "Slowpoke", .max_health = 90, .catch_rate = 190},
    {.name = "Slowbro", .max_health = 95, .catch_rate = 75},
    {.name = "Magnemite", .max_health = 25, .catch_rate = 190},
    {.name = "Magneton", .max_health = 50, .catch_rate = 60},
    {.name = "Farfetchd", .max_health = 52, .catch_rate = 45},
    {.name = "Doduo", .max_health = 35, .catch_rate = 190},
    {.name = "Dodrio", .max_health = 60, .catch_rate = 45},
    {.name = "Seel", .max_health = 65, .catch_rate = 190},
    {.name = "Dewgong", .max_health = 90, .catch_rate = 75},
    {.name = "Grimer", .max_health = 80, .catch_rate = 190},
    {.name = "Muk", .max_health = 105, .catch_rate = 75},
    {.name = "Shellder", .max_health = 30, .catch_rate = 190},
    {.name = "Cloyster", .max_health = 50, .catch_rate = 60},
    {.name = "Gastly", .max_health = 30, .catch_rate = 190},
    {.name = "Haunter", .max_health = 45, .catch_rate = 90},
    {.name = "Gengar", .max_health = 60, .catch_rate = 45},
    {.name = "Onix", .max_health = 35, .catch_rate = 45},
    {.name = "Drowzee", .max_health = 60, .catch_rate = 190},
    {.name = "Hypno", .max_health = 85, .catch_rate = 75},
    {.name = "Krabby", .max_health = 30, .catch_rate = 225},
    {.name = "Kingler", .max_health = 55, .catch_rate = 60},
    {.name = "Voltorb", .max_health = 40, .catch_rate = 190},
    {.name = "Electrode", .max_health = 60, .catch_rate = 60},
    {.name = "Exeggcute", .max_health = 60, .catch_rate = 90},
    {.name = "Exeggutor", .max_health = 95, .catch_rate = 45},
    {.name = "Cubone", .max_health = 50, .catch_rate = 190},
    {.name = "Marowak", .max_health = 60, .catch_rate = 75},
    {.name = "Hitmonlee", .max_health = 50, .catch_rate = 45},
    {.name = "Hitmonchan", .max_health = 50, .catch_rate = 45},
    {.name = "Lickitung", .max_health = 90, .catch_rate = 45},
    {.name = "Koffing", .max_health = 40, .catch_rate = 190},
    {.name = "Weezing", .max_health = 65, .catch_rate = 60},
    {.name = "Rhyhorn", .max_health = 80, .catch_rate = 120},
    {.name = "Rhydon", .max_health = 105, .catch_rate = 60},
    {.name = "Chansey", .max_health = 250, .catch_rate = 30},
    {.name = "Tangela", .max_health = 65, .catch_rate = 45},
    {.name = "Kangaskhan", .max_health = 105, .catch_rate = 45},
    {.name = "Horsea", .max_health = 30, .catch_rate = 225},
    {.name = "Seadra", .max_health = 55, .catch_rate = 75},
    {.name = "Goldeen", .max_health = 45, .catch_rate = 225},
    {.name = "Seaking", .max_health = 80, .catch_rate = 60},
    {.name = "Staryu", .max_health = 30, .catch_rate = 225},
    {.name = "Starmie", .max_health = 60, .catch_rate = 60},
    {.name = "MrMime", .max_health = 40, .catch_rate = 45},
    {.name = "Scyther", .max_health = 70, .catch_rate = 45},
    {.name = "Jynx", .max_health = 65, .catch_rate = 45},
    {.name = "Electabuzz", .max_health = 65, .catch_rate = 45},
    {.name = "Magmar", .max_health = 65, .catch_rate = 45},
    {.name = "Pinsir", .max_health = 65, .catch_rate = 45},
    {.name = "Tauros", .max_health = 75, .catch_rate = 45},
    {.name = "Magikarp", .max_health = 20, .catch_rate = 255},
    {.name = "Gyarados", .max_health = 95, .catch_rate = 45},
    {.name = "Lapras", .max_health = 130, .catch_rate = 45},
    {.name = "Ditto", .max_health = 48, .catch_rate = 35},
    {.name = "Eevee", .max_health = 55, .catch_rate = 45},
    {.name = "Vaporeon", .max_health = 130, .catch_rate = 45},
    {.name = "Jolteon", .max_health = 65, .catch_rate = 45},
    {.name = "Flareon", .max_health = 65, .catch_rate = 45},
    {.name = "Porygon", .max_health = 65, .catch_rate = 45},
    {.name = "Omanyte", .max_health = 35, .catch_rate = 45},
    {.name = "Omastar", .max_health = 70, .catch_rate = 45},
    {.name = "Kabuto", .max_health = 30, .catch_rate = 45},
    {.name = "Kabutops", .max_health = 60, .catch_rate = 45},
    {.name = "Aerodactyl", .max_health = 80, .catch_rate = 45},
    {.name = "Snorlax", .max_health = 160, .catch_rate = 25},
    {.name = "Articuno", .max_health = 90, .catch_rate = 3},
    {.name = "Zapdos", .max_health = 90, .catch_rate = 3},
    {.name = "Moltres", .max_health = 90, .catch_rate = 3},
    {.name = "Dratini", .max_health = 41, .catch_rate = 45},
    {.name = "Dragonair", .max_health = 61, .catch_rate = 45},
    {.name = "Dragonite", .max_health = 91, .catch_rate = 45},
    {.name = "Mewtwo", .max_health = 106, .catch_rate = 3},
    {.name = "Mew", .max_health = 100, .catch_rate = 45}
};
